# Copyright 2025 Shuai Zhang
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

default: true

# Heading levels should only increment by one level at a time
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md001.md
MD001: true

# Heading style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md003.md
MD003:
  style: atx

# Unordered list style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md004.md
MD004:
  style: consistent

# Inconsistent indentation for list items at the same level
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md005.md
MD005: true

# Unordered list indentation
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md007.md
MD007:
  indent: 4
  start_indented: false

# Trailing spaces
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md009.md
MD009:
  br_spaces: 4
  list_item_empty_lines: false
  strict: true

# Hard tabs
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md010.md
MD010:
  code_blocks: true
  spaces_per_tab: 4

# Reversed link syntax
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md011.md
MD011: true

# Multiple consecutive blank lines
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md012.md
MD012:
  maximum: 1

# Line length
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  line_length: 2147483647
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: false
  headings: true
  strict: false
  stern: false

# Dollar signs used before commands without showing output
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md014.md
MD014: true

# No space after hash on atx style heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md018.md
MD018: true

# Multiple spaces after hash on atx style heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md019.md
MD019: true

# No space inside hashes on closed atx style heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md020.md
MD020: true

# Multiple spaces inside hashes on closed atx style heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md021.md
MD021: true

# Headings should be surrounded by blank lines
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md022.md
MD022:
  lines_above: 1
  lines_below: 1

# Headings must start at the beginning of the line
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md023.md
MD023: true

# Multiple headings with the same content
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md024.md
MD024:
  siblings_only: true

# Multiple top-level headings in the same document
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md025.md
MD025:
  level: 1

# Trailing punctuation in heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md026.md
MD026:
  punctuation: '.,;:!。，；：！'

# Multiple spaces after blockquote symbol
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md027.md
MD027: true

# Blank line inside blockquote
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md028.md
MD028: true

# Ordered list item prefix
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md029.md
MD029:
  style: one_or_ordered

# Spaces after list markers
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md030.md
MD030:
  ul_single: 1
  ul_multi: 1
  ol_single: 1
  ol_multi: 1

# Fenced code blocks should be surrounded by blank lines
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md031.md
MD031:
  list_items: true

# Lists should be surrounded by blank lines
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md032.md
MD032: true

# Inline HTML
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md033.md
MD033:
  allowed_elements: []

# Bare URL used
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md034.md
MD034: false

# Horizontal rule style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md035.md
MD035:
  style: '---'

# Emphasis used instead of a heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md036.md
MD036:
  punctuation: '.,;:!?。，；：！？'

# Spaces inside emphasis markers
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md037.md
MD037: true

# Spaces inside code span elements
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md038.md
MD038: true

# Spaces inside link text
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md039.md
MD039: true

# Fenced code blocks should have a language specified
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md040.md
MD040:
  language_only: true

# First line in a file should be a top-level heading
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md041.md
MD041:
  level: 1

# No empty links
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md042.md
MD042: true

# Required heading structure
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md043.md

# Proper names should have the correct capitalization
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md044.md
MD044:
  code_blocks: false
  names:
    - JavaScript
    - Python
    - SuperBench

# Images should have alternate text (alt text)
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md045.md
MD045: true

# Code block style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md046.md
MD046:
  style: fenced

# Files should end with a single newline character
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md047.md
MD047: true

# Code fence style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md048.md
MD048:
  style: backtick

# Emphasis style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md049.md
MD049:
  style: underscore

# Strong style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md050.md
MD050:
  style: asterisk

# Link fragments should be valid
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md051.md
MD051: true

# Reference links and images should use a label that is defined
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md052.md
MD052:
  shortcut_syntax: false

# Link and image reference definitions should be needed
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md053.md
MD053:
  ignored_definitions:
    - '//'

# Link and image style
# https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md054.md
MD054:
  autolink: true
  inline: true
  full: true
  collapsed: true
  shortcut: true
  url_inline: true

# Table pipe style
# https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md055.md
MD055:
  style: leading_and_trailing

# Table column count
# https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md056.md
MD056: true

# Tables should be surrounded by blank lines
# https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md058.md
MD058: true

# Link text should be descriptive
# https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md059.md
MD059: true

# Table column style
# https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md060.md
#
# Temporary disable due to bug in markdownlint v0.39.0
# Prettier will ensure table column alignment
MD060: false
